service: multiple-dynamodb-proxy

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  localPath: './../../../../../../'
  modules:
    - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - dynamodb:
        path: /dynamodb/{id}/{sort}
        method: put
        tableName:
          Ref: MyMuTestTable
        hashKey:
          pathParam: id
          attributeType: S
        rangeKey:
          pathParam: sort
          attributeType: S
        action: PutItem
        cors: true
    - dynamodb:
        path: /dynamodb
        method: get
        tableName:
          Ref: MyMuTestTable
        action: GetItem
        hashKey:
          queryStringParam: id
          attributeType: S
        rangeKey:
          queryStringParam: sort
          attributeType: S
        cors: true
    - dynamodb:
        path: /dynamodb/index/{indexRange}/{indexSort}
        method: get
        indexName: myTestIndex
        tableName:
          Ref: MyMuTestTable
        action: Query
        hashKey:
          pathParam: indexSort
          attributeType: S
        rangeKey:
          pathParam: indexRange
          attributeType: S
        cors: true
    - dynamodb:
        path: /dynamodb/{id}
        method: delete
        tableName:
          Ref: MyMuTestTable
        action: DeleteItem
        hashKey:
          pathParam: id
          attributeType: S
        rangeKey:
          queryStringParam: sort
          attributeType: S
        cors: true

resources:
  Resources:
    MyMuTestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MyMuTestTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: sort
            AttributeType: S
          - AttributeName: indexRange
            AttributeType: S
          - AttributeName: indexSort
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: sort
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: myTestIndex
            KeySchema:
              - AttributeName: indexSort
                KeyType: HASH
              - AttributeName: indexRange
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
